// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/audio-factory-redesign/CollaborativePluginReview.tsx": () => import("../components/mockups/audio-factory-redesign/CollaborativePluginReview.tsx"),
  "./components/mockups/audio-factory-redesign/CompactReviewTabs.tsx": () => import("../components/mockups/audio-factory-redesign/CompactReviewTabs.tsx"),
  "./components/mockups/audio-factory-redesign/Current.tsx": () => import("../components/mockups/audio-factory-redesign/Current.tsx"),
  "./components/mockups/audio-factory-redesign/ExpandedAuditTimeline.tsx": () => import("../components/mockups/audio-factory-redesign/ExpandedAuditTimeline.tsx"),
  "./components/mockups/audio-factory-redesign/GuidedBuildFlow.tsx": () => import("../components/mockups/audio-factory-redesign/GuidedBuildFlow.tsx"),
  "./components/mockups/audio-factory-redesign/LiveHardwareRack.tsx": () => import("../components/mockups/audio-factory-redesign/LiveHardwareRack.tsx"),
  "./components/mockups/audio-factory-redesign/LivePluginWorkbench.tsx": () => import("../components/mockups/audio-factory-redesign/LivePluginWorkbench.tsx"),
  "./components/mockups/audio-factory-redesign/ModulationMatrix.tsx": () => import("../components/mockups/audio-factory-redesign/ModulationMatrix.tsx"),
  "./components/mockups/audio-factory-redesign/SignoffLedger.tsx": () => import("../components/mockups/audio-factory-redesign/SignoffLedger.tsx"),
  "./components/mockups/audio-factory-redesign/Upgraded.tsx": () => import("../components/mockups/audio-factory-redesign/Upgraded.tsx"),
  "./components/mockups/audio-factory-redesign-signal-flow/AnimatedModulationMatrix.tsx": () => import("../components/mockups/audio-factory-redesign-signal-flow/AnimatedModulationMatrix.tsx"),
  "./components/mockups/audio-factory-redesign-signal-flow-compact/CompactSignalFlowMatrix.tsx": () => import("../components/mockups/audio-factory-redesign-signal-flow-compact/CompactSignalFlowMatrix.tsx"),
  "./components/mockups/audio-factory-release-handoff/PrintableReleaseHandoff.tsx": () => import("../components/mockups/audio-factory-release-handoff/PrintableReleaseHandoff.tsx"),
  "./components/mockups/audio-factory-release-handoff/ReleaseHandoffBroadcast.tsx": () => import("../components/mockups/audio-factory-release-handoff/ReleaseHandoffBroadcast.tsx"),
  "./components/mockups/audio-factory-release-handoff/ReleaseHandoffCommandCenter.tsx": () => import("../components/mockups/audio-factory-release-handoff/ReleaseHandoffCommandCenter.tsx"),
  "./components/mockups/audio-factory-release-handoff-lounge/ReleaseHandoffListeningLounge.tsx": () => import("../components/mockups/audio-factory-release-handoff-lounge/ReleaseHandoffListeningLounge.tsx"),
  "./components/mockups/templates/FinanceAILandingPage-aUVpyi/Claros.tsx": () => import("../components/mockups/templates/FinanceAILandingPage-aUVpyi/Claros.tsx"),
  "./components/mockups/templates/MemphisMealKitLandingPage-kKOI-l/App.tsx": () => import("../components/mockups/templates/MemphisMealKitLandingPage-kKOI-l/App.tsx"),
  "./components/mockups/templates/SwissBreathworkLandingPage-q9Ds35/App.tsx": () => import("../components/mockups/templates/SwissBreathworkLandingPage-q9Ds35/App.tsx")
};
