/**
 * Deterministic portable-code scaffolds (Faust + JUCE C++).
 *
 * Faust/C++ used to be generated by the LLM on EVERY chat generation, tripling
 * output tokens for artifacts only needed at export time. Now the export tab
 * asks the local model to translate the JS lazily -- and when no model is
 * reachable, these category-matched scaffolds ship instantly so the Export
 * panel is never empty. They are real, compilable starting points (parameter
 * declarations plus a faithful category-default signal chain), with the exact
 * JS algorithm embedded as the reference for hand-porting.
 */

import { AudioPlugin, PluginParameter } from "../types";

function faustSliderName(p: PluginParameter): string {
  return p.id.replace(/[^a-zA-Z0-9_]/g, "_");
}

function faustStep(p: PluginParameter): number {
  const span = p.max - p.min;
  if (span <= 2) return 0.01;
  if (span <= 100) return 0.1;
  return 1;
}

function findParam(params: PluginParameter[], ...patterns: RegExp[]): PluginParameter | undefined {
  for (const pattern of patterns) {
    const hit = params.find((p) => pattern.test(p.id) || pattern.test(p.name));
    if (hit) return hit;
  }
  return undefined;
}

/** Reference a declared slider by variable name, or fall back to a literal. */
function ref(p: PluginParameter | undefined, fallback: string): string {
  return p ? faustSliderName(p) : fallback;
}

export function buildFaustScaffold(plugin: AudioPlugin): string {
  const params = plugin.parameters.filter((p) => p.min !== p.max);
  const sliders = params
    .map(
      (p) =>
        `${faustSliderName(p)} = hslider("${p.name} [unit:${p.unit || ""}]", ${p.defaultValue}, ${p.min}, ${p.max}, ${faustStep(p)}) : si.smoo;`
    )
    .join("\n");

  const drive = findParam(params, /drive|gain|input/i);
  const mix = findParam(params, /mix|blend|dry_wet/i);
  const cutoff = findParam(params, /cutoff|freq|tone/i);
  const res = findParam(params, /reson|q\b|peak/i);
  const time = findParam(params, /time|delay/i);
  const feedback = findParam(params, /feedback|decay|regen/i);
  const threshold = findParam(params, /thresh/i);
  const ratio = findParam(params, /ratio/i);
  const rate = findParam(params, /rate|speed|lfo/i);
  const depth = findParam(params, /depth|amount|intensity/i);

  let chain: string;
  switch (plugin.category) {
    case "distortion":
      chain = `wet = _ : *(ba.db2linear(${ref(drive, "12.0")})) : ma.tanh : fi.lowpass(1, 9000) : *(0.7);
process = _ <: (_, wet) : si.interpolate(${ref(mix, "0.8")});`;
      break;
    case "delay":
      chain = `maxDel = 96000;
delSamps = ${ref(time, "350.0")} * ma.SR / 1000.0;
wet = _ : (+ : de.fdelay(maxDel, delSamps)) ~ (*(${ref(feedback, "0.45")}) : fi.lowpass(1, 6500));
process = _ <: (_, wet) : si.interpolate(${ref(mix, "0.4")});`;
      break;
    case "filter":
      chain = `process = _ : fi.resonlp(${ref(cutoff, "1200.0")}, ${ref(res, "1.0")}, 1.0) : ma.tanh;`;
      break;
    case "dynamics":
      chain = `process = _ : co.compressor_mono(${ref(ratio, "4.0")}, ${ref(threshold, "-18.0")}, 0.010, 0.120);`;
      break;
    case "modulation":
      chain = `lfo = os.osc(${ref(rate, "1.5")}) * ${ref(depth, "0.5")};
wet = _ : de.fdelay(4096, 220.0 + lfo * 180.0);
process = _ <: (_, wet) : si.interpolate(${ref(mix, "0.5")});`;
      break;
    case "reverb":
      chain = `wet = _ : re.mono_freeverb(0.84, 0.6, 0.4, 0);
process = _ <: (_, wet) : si.interpolate(${ref(mix, "0.35")});`;
      break;
    case "synthesizer":
    default:
      chain = `process = _ : ma.tanh;`;
      break;
  }

  return `// ${plugin.name} -- Faust reference scaffold (category: ${plugin.category})
// Auto-generated deterministic starting point. The authoritative algorithm is
// the JavaScript below; regenerate a faithful translation from the Export tab
// with a local model connected, or port by hand using this scaffold.
import("stdfaust.lib");

${sliders}

${chain}

/* REFERENCE ALGORITHM (JavaScript, per-sample, 44100 Hz):
${plugin.dspFunction.replace(/\*\//g, "* /")}
*/
`;
}

function cppIdent(p: PluginParameter): string {
  const cleaned = p.id.replace(/[^a-zA-Z0-9_]/g, "_");
  // A C++ identifier can't start with a digit -- confirmed the exact same
  // guard already exists in server/nativeBuild.ts's cppIdentifier() but was
  // never ported here; a numeric-led param id (e.g. a sanitized "1x12"-
  // style id) would otherwise emit an illegal declaration.
  return /^[0-9]/.test(cleaned) ? `p_${cleaned}` : cleaned;
}

/** Valid C++ float literal: integers need the decimal point ("20f" is a
 *  compile error -- C3688 -- "20.0f" is not). Same helper as
 *  server/nativeBuild.ts's cppFloat(), ported verbatim rather than
 *  reinvented -- that file already fixed this exact defect, it just never
 *  propagated to this sibling generator, which is why every whole-number
 *  parameter default (dB/ms/Hz/ratio-count -- the common case) shipped an
 *  invalid literal ("3f" instead of "3.0f") in every scaffold this
 *  function produced. */
function cppFloat(n: number): string {
  const v = Number(n) || 0;
  return `${v}${Number.isInteger(v) ? ".0" : ""}f`;
}

export function buildJuceScaffold(plugin: AudioPlugin): string {
  const params = plugin.parameters.filter((p) => p.min !== p.max);
  const className = (plugin.name || "Generated").replace(/[^a-zA-Z0-9]/g, "") + "Processor";

  const paramDecls = params
    .map((p) => `    float ${cppIdent(p)} = ${cppFloat(p.defaultValue)}; // "${p.name}" [${p.min} .. ${p.max}] ${p.unit || ""}`)
    .join("\n");

  const smoothDecls = params.map((p) => `    juce::SmoothedValue<float> ${cppIdent(p)}Smooth;`).join("\n");

  const smoothInit = params
    .map((p) => `        ${cppIdent(p)}Smooth.reset(sampleRate, 0.02);\n        ${cppIdent(p)}Smooth.setCurrentAndTargetValue(${cppIdent(p)});`)
    .join("\n");

  return `// ${plugin.name} -- JUCE C++ reference scaffold (category: ${plugin.category})
// Auto-generated deterministic starting point: real-time-safe shell with
// parameter smoothing and the authoritative JS algorithm embedded below.
// Regenerate a faithful translation from the Export tab with a local model
// connected, or port the per-sample math into processSample() by hand.
#pragma once
#include <juce_dsp/juce_dsp.h>
#include <cmath>

class ${className}
{
public:
${paramDecls}

    void prepare (double newSampleRate)
    {
        sampleRate = newSampleRate;
${smoothInit}
        reset();
    }

    void reset()
    {
        z1 = 0.0f;
        z2 = 0.0f;
    }

    // Per-sample processing, mirrors: function(inputSample, params, state)
    float processSample (float inputSample) noexcept
    {
${params.map((p) => `        const float ${cppIdent(p)}Now = ${cppIdent(p)}Smooth.getNextValue(); juce::ignoreUnused(${cppIdent(p)}Now);`).join("\n")}

        // TODO(port): implement the reference algorithm below using the
        // smoothed parameter values. Passthrough with a safety limiter until
        // the port is complete keeps the plugin loadable at every step.
        float y = inputSample;
        return std::tanh (y);
    }

    void processBlock (juce::AudioBuffer<float>& buffer) noexcept
    {
        juce::ScopedNoDenormals noDenormals;
${params.map((p) => `        ${cppIdent(p)}Smooth.setTargetValue(${cppIdent(p)});`).join("\n")}
        for (int ch = 0; ch < buffer.getNumChannels(); ++ch)
        {
            auto* data = buffer.getWritePointer (ch);
            for (int i = 0; i < buffer.getNumSamples(); ++i)
                data[i] = sanitizeSample (processSample (data[i]));
        }
    }

private:
    // Safety net: guarantees every sample written to the host's audio buffer
    // is finite, denormal-free, and bounded. This is the last line of
    // defense against a runaway filter, an unstable feedback path, or a
    // divide-by-zero landing on a bad coefficient in the ported DSP above --
    // never a mixing/loudness decision, just a floor that a correctly
    // behaving plugin should never actually hit. Applied unconditionally to
    // every output sample, for every channel, right before it reaches the
    // buffer.
    static inline float sanitizeSample (float x) noexcept
    {
        if (! std::isfinite (x))
            return 0.0f;

        if (std::abs (x) < 1.0e-30f)
            return 0.0f; // flush denormals to zero -- avoids FPU stalls on x86

        return juce::jlimit (-4.0f, 4.0f, x);
    }

    double sampleRate = 44100.0;
    float z1 = 0.0f, z2 = 0.0f;
${smoothDecls}
};

/* REFERENCE ALGORITHM (JavaScript, per-sample, 44100 Hz):
${plugin.dspFunction.replace(/\*\//g, "* /")}
*/
`;
}

export function buildPortableScaffolds(plugin: AudioPlugin): { faustCode: string; cppJuceCode: string } {
  return {
    faustCode: buildFaustScaffold(plugin),
    cppJuceCode: buildJuceScaffold(plugin),
  };
}
